name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # - name: Set environmental variables
      #   run: |
      #     if [ ${{ secrets.VITE_APP_ENVIRONMENT }} = "DEV" ]; then
      #       echo "VITE_API_KEY=${{ secrets.VITE_DEV_API_KEY }}" >> $GITHUB_ENV
      #       echo "VITE_APP_ID=${{ secrets.VITE_DEV_APP_ID }}" >> $GITHUB_ENV
      #       echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_DEV_AUTH_DOMAIN }}" >> $GITHUB_ENV
      #       echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_DEV_MEASUREMENT_ID }}" >> $GITHUB_ENV
      #       echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_DEV_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
      #       echo "VITE_PROJECT_ID=${{ secrets.VITE_DEV_PROJECT_ID }}" >> $GITHUB_ENV
      #       echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_DEV_STORAGE_BUCKET }}" >> $GITHUB_ENV
      #     else
      #       echo "VITE_API_KEY=${{ secrets.VITE_PROD_API_KEY }}" >> $GITHUB_ENV
      #       echo "VITE_APP_ID=${{ secrets.VITE_PROD_APP_ID }}" >> $GITHUB_ENV
      #       echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_PROD_AUTH_DOMAIN }}" >> $GITHUB_ENV
      #       echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_PROD_MEASUREMENT_ID }}" >> $GITHUB_ENV
      #       echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_PROD_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
      #       echo "VITE_PROJECT_ID=${{ secrets.VITE_PROD_PROJECT_ID }}" >> $GITHUB_ENV
      #       echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_PROD_STORAGE_BUCKET }}" >> $GITHUB_ENV
      #     fi

      - env:
          VITE_APP_ENVIRONMENT: ${{ secrets.VITE_DEV_APP_ENVIRONMENT }}
          VITE_DEV_API_KEY: ${{ secrets.VITE_DEV_API_KEY }}
          VITE_DEV_APP_ID: ${{ secrets.VITE_DEV_APP_ID }}
          VITE_DEV_AUTH_DOMAIN: ${{ secrets.VITE_DEV_AUTH_DOMAIN }}
          VITE_DEV_MEASUREMENT_ID: ${{ secrets.VITE_DEV_MEASUREMENT_ID }}
          VITE_DEV_MESSAGING_SENDER_ID: ${{ secrets.VITE_DEV_MESSAGING_SENDER_ID }}
          VITE_DEV_PROJECT_ID: ${{ secrets.VITE_DEV_PROJECT_ID }}
          VITE_DEV_STORAGE_BUCKET: ${{ secrets.VITE_DEV_STORAGE_BUCKET }}
          VITE_PROD_API_KEY: ${{ secrets.VITE_PROD_API_KEY }}
          VITE_PROD_APP_ID: ${{ secrets.VITE_PROD_APP_ID }}
          VITE_PROD_AUTH_DOMAIN: ${{ secrets.VITE_PROD_AUTH_DOMAIN }}
          VITE_PROD_MEASUREMENT_ID: ${{ secrets.VITE_PROD_MEASUREMENT_ID }}
          VITE_PROD_MESSAGING_SENDER_ID: ${{ secrets.VITE_PROD_MESSAGING_SENDER_ID }}
          VITE_PROD_PROJECT_ID: ${{ secrets.VITE_PROD_PROJECT_ID }}
          VITE_PROD_STORAGE_BUCKET: ${{ secrets.VITE_PROD_STORAGE_BUCKET }}


      - name: Confirm proper variables were set
        run: |
          echo "VITE_APP_ENVIRONMENT: $VITE_APP_ENVIRONMENT"
          echo "APP_ID: $APP_ID"

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist